apiVersion: v1
kind: Service
metadata:
  name: hsbc-trade-service
spec:
  selector:
    app: hsbc-trade
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hsbc-trade-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: hsbc-trade
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 20

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hsbc-trade
spec:
  serviceName: "hsbc-trade-service"
  replicas: 1
  selector:
    matchLabels:
      app: hsbc-trade
  template:
    metadata:
      labels:
        app: hsbc-trade
    spec:
      containers:
        - name: hsbc-trade
          image: 127.0.0.1:5001/hsbc-trade:latest
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "2"
            limits:
              memory: "256Mi"
              cpu: "2"
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: log-storage
              mountPath: /var/log/java
          env:
            - name: JAVA_OPTS
              value: "-Djava.awt.headless=true -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+AlwaysPreTouch"
          # 其他环境变量和配置...
      imagePullSecrets:
        - name: registry-secret
  volumeClaimTemplates:
    - metadata:
        name: log-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
